#!/usr/bin/env node
// Builds the ChatGPT Sites page from my-gym.html (shared app + Claude adapter): the block between
// "// ==== ADAPTER START" and "// ==== ADAPTER END ====" is replaced with sites/adapter.js.
// Outputs: sites/public/index.html (static page) and sites/src/page.ts (the same page as a module for the Worker).
// Usage: node build.mjs            writes both files
//        node build.mjs --check    fails if the committed outputs are out of date
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(fileURLToPath(import.meta.url));
const src = fs.readFileSync(path.join(root, "my-gym.html"), "utf8");
const adapter = fs.readFileSync(path.join(root, "sites", "adapter.js"), "utf8");

const startMark = "// ==== ADAPTER START";
const endMark = "// ==== ADAPTER END ====";
const start = src.indexOf(startMark);
const end = src.indexOf(endMark);
if (start < 0 || end < 0 || end < start) throw new Error("adapter markers not found in my-gym.html");
if (!adapter.startsWith("// ==== ADAPTER START: ChatGPT Sites") || !adapter.trimEnd().endsWith(endMark)) {
  throw new Error("sites/adapter.js must start with '// ==== ADAPTER START: ChatGPT Sites' and end with '" + endMark + "'");
}

const page = src.slice(0, start) + adapter.trimEnd() + src.slice(end + endMark.length);
if (page.includes("window.claude")) throw new Error("the Sites page still references window.claude");
if (!page.includes("var ANAME = ADAPTER.assistantName")) throw new Error("shared start section missing after the adapter block");

const outputs = {
  "sites/public/index.html": page,
  "sites/src/page.ts":
    "// GENERATED by build.mjs from my-gym.html and sites/adapter.js. Do not edit; edit the sources and run: node build.mjs\n" +
    "export const PAGE: string = " + JSON.stringify(page) + ";\n",
};

const check = process.argv.includes("--check");
let stale = 0;
for (const [rel, content] of Object.entries(outputs)) {
  const file = path.join(root, rel);
  if (check) {
    const current = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : null;
    if (current !== content) { console.error("out of date: " + rel + " (run: node build.mjs)"); stale++; }
  } else {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
    console.log("wrote " + rel + " (" + content.length + " chars)");
  }
}
if (check) { if (stale) process.exit(1); console.log("generated files are up to date"); }
